{
 "title": "Java Processor Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_message_seconds_count[1m])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_message_seconds_sum[1m])/rate(process_message_seconds_count[1m])",
     "legendFormat": "Average Response Time"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "Heap Memory Used"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "Heap Memory Max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "System CPU" },
    { "expr": "process_cpu_usage", "legendFormat": "Process CPU" }
   ]
  }
 ]
}